'use client';
import Link from 'next/link';
import HeroSculpture from './HeroSculpture';
import Image from 'next/image';
import { useEffect, useRef, useState } from 'react';
type Locale = 'pt' | 'en';
const text = {
 pt: {nav:['Projetos','Sobre','Contato'],available:'Aberto a oportunidades remotas',hero:'Código com',heroEnd:'propósito.',sub:'Produtos em evolução.',intro:'Sou Daniel Neri, desenvolvedor Full Stack. Conecto interfaces, serviços e infraestrutura para transformar problemas em produtos.',explore:'Explorar projetos',resume:'Currículo',selected:'01 / TRABALHOS SELECIONADOS',workTitle:'Da ideia ao',workEnd:'produto.',workIntro:'Projetos próprios e experiências em sociedade. O contexto, minha contribuição e o estágio real de cada produto.',filters:['Todos','Em desenvolvimento','Encerrados'],case:'Ver estudo técnico',scope:'Minha atuação',scopeText:'Responsável por toda a parte técnica e operacional: design, frontend, backend, integrações e infraestrutura.',challenge:'O desafio',built:'O que desenvolvi',learn:'Aprendizado',visit:'Visitar site',capture:'Captura real do site',previous:'Interface atual · reboot em Godot / 2.5D · em desenvolvimento',aboutLabel:'02 / SOBRE MIM',aboutTitle:'Visão de produto.',aboutEnd:'Mão no código.',aboutText:'Minha trajetória combina desenvolvimento freelance e construção de produtos próprios. Trabalhei do design de interface à operação dos sistemas, acompanhando as decisões técnicas ao longo de cada projeto.',aboutText2:'Estou no último semestre de Análise e Desenvolvimento de Sistemas na UNIP, com conclusão prevista para dezembro de 2026. Busco integrar uma equipe de engenharia, contribuir com entregas e evoluir com colaboração e revisão técnica.',degree:'ADS · UNIP',degreeSub:'Conclusão prevista: dezembro de 2026',english:'Inglês C1',englishSub:'Um ano de estudos na EF English e prática contínua',location:'Belém, Pará',locationSub:'Brasil · oportunidades remotas',toolbox:'FERRAMENTAS DE TRABALHO',contactLabel:'03 / PRÓXIMO PASSO',contactTitle:'Vamos construir',contactEnd:'algo juntos.',contactText:'Procurando alguém que conecte frontend, backend e produto? Estou aberto a conversar sobre oportunidades de desenvolvimento.',email:'Enviar e-mail',copy:'Copiar e-mail',copied:'E-mail copiado',copyError:'Use o link de e-mail',footer:'Desenvolvido por Daniel Neri.',back:'Voltar ao topo',portrait:'Retrato profissional de Daniel Neri',archived:'Projeto encerrado',founder:'Projeto próprio · fundador',partner:'Projeto em sociedade',docs:'Currículo para candidaturas',skip:'Ir para o conteúdo',viewSource:'Código público',close:'Fechar estudo técnico'},
 en: {nav:['Projects','About','Contact'],available:'Open to remote opportunities',hero:'Code with',heroEnd:'purpose.',sub:'Products in progress.',intro:'I’m Daniel Neri, a Full Stack Developer. I connect interfaces, services and infrastructure to turn problems into products.',explore:'Explore projects',resume:'Resume',selected:'01 / SELECTED WORK',workTitle:'From idea to',workEnd:'product.',workIntro:'Independent products and partnership projects. The context, my contribution and the actual stage of each product.',filters:['All','In development','Archived'],case:'Read engineering study',scope:'My contribution',scopeText:'Responsible for all technical and operational work: design, frontend, backend, integrations and infrastructure.',challenge:'The challenge',built:'What I built',learn:'What I learned',visit:'Visit website',capture:'Actual website capture',previous:'Current interface · Godot / 2.5D reboot · in development',aboutLabel:'02 / ABOUT ME',aboutTitle:'Product thinking.',aboutEnd:'Hands-on engineering.',aboutText:'My background combines freelance development and building independent products. I have worked from interface design through system operations, following technical decisions throughout each project.',aboutText2:'I’m in the final semester of Systems Analysis and Development at UNIP, with graduation expected in December 2026. I’m looking to join an engineering team, contribute to delivery and grow through collaboration and technical review.',degree:'Systems Analysis & Development · UNIP',degreeSub:'Expected graduation: December 2026',english:'English C1',englishSub:'One year studying at EF English, with continued practice',location:'Belém, Pará',locationSub:'Brazil · remote opportunities',toolbox:'MY WORKING TOOLBOX',contactLabel:'03 / NEXT STEP',contactTitle:'Let’s build',contactEnd:'something together.',contactText:'Looking for someone who connects frontend, backend and product? I’m open to discussing software development opportunities.',email:'Send an email',copy:'Copy email',copied:'Email copied',copyError:'Use the email link',footer:'Developed by Daniel Neri.',back:'Back to top',portrait:'Professional portrait of Daniel Neri',archived:'Archived project',founder:'Independent product · founder',partner:'Partnership project',docs:'Application resume',skip:'Skip to content',viewSource:'Public source',close:'Close engineering study'}
};
const projects = [
 {id:'zapyflow',name:'Zapyflow',category:'active',role:'founder',kind:{pt:'AUTOMAÇÃO / SAAS',en:'AUTOMATION / SAAS'},status:{pt:'Em desenvolvimento contínuo',en:'Ongoing development'},description:{pt:'Operações de atendimento e automação pelo WhatsApp, com IA, CRM e fluxos visuais.',en:'WhatsApp support and automation operations, combining AI, CRM and visual workflows.'},stack:['React','TypeScript','Fastify','Prisma','WhatsApp Cloud API'],image:'/media/zapyflow.jpg',url:'https://zapyflow.com.br',challenge:{pt:'Conectar conversas, dados de leads e automações em uma experiência de operação que permita o atendimento humano quando necessário.',en:'Connect conversations, lead data and automation in an operational experience that allows human handoff when needed.'},built:{pt:['Interface de operação em React, com CRM e editor visual de fluxos.','API em TypeScript/Fastify, persistência com Prisma e integrações com WhatsApp Cloud API.','Fluxos de atendimento com IA, base de conhecimento e transferência para operadores.'],en:['React operational interface with CRM and a visual workflow editor.','TypeScript/Fastify API, Prisma persistence and WhatsApp Cloud API integrations.','AI support flows, a knowledge base and handoff to human operators.']},learn:{pt:'Projetar automações exige tratar estados, falhas de integração e intervenção humana como parte do produto.',en:'Designing automation means treating states, integration failures and human intervention as part of the product.'}},
 {id:'vettano',name:'Vettano',category:'active',role:'founder',kind:{pt:'JOGOS / TEMPO REAL',en:'GAMES / REAL TIME'},status:{pt:'Reboot · Godot / 2.5D',en:'Reboot · Godot / 2.5D'},description:{pt:'Jogo social de desenho e adivinhação. Em reboot, migrando de React para Godot com visual 2.5D.',en:'A social drawing and guessing game. Currently being rebooted, moving from React to Godot with a 2.5D visual direction.'},stack:['Go','Godot / C#','PostgreSQL','Redis','NATS'],image:'/media/vettano-home.webp',url:'https://vettano.com',challenge:{pt:'Coordenar sessões, partidas e estados em tempo real, preservando a consistência entre clientes e serviços.',en:'Coordinate sessions, matches and real-time state while preserving consistency between clients and services.'},built:{pt:['Serviços em Go para autenticação, lobby, partidas e recursos sociais.','Infraestrutura com PostgreSQL, Redis e NATS; cliente web anterior em React.','Reboot em andamento: cliente Godot/C# e redesign da experiência em 2.5D.'],en:['Go services for authentication, lobbies, matches and social features.','Infrastructure with PostgreSQL, Redis and NATS; previous web client in React.','Reboot in progress: a Godot/C# client and a redesigned 2.5D experience.']},learn:{pt:'A evolução do produto também envolve rever a tecnologia do cliente e a linguagem visual, mantendo a base de serviços.',en:'Product evolution also involves revisiting client technology and visual language while retaining the service foundation.'}},
 {id:'infinity',name:'Infinity Boost',image:'/media/infinity-home.jpg',category:'archived',role:'partner',kind:{pt:'MARKETPLACE / ESTUDO TÉCNICO',en:'MARKETPLACE / ENGINEERING STUDY'},status:{pt:'Encerrado',en:'Archived'},description:{pt:'Marketplace de serviços para jogos, com pedidos, ofertas, chat e integração de pagamentos.',en:'A marketplace for gaming services, with orders, offers, chat and payment integration.'},stack:['Next.js','Go / Gin','PostgreSQL','WebSocket','Stripe'],challenge:{pt:'Organizar a negociação entre clientes e prestadores, conectando ofertas, pedidos, conversas e pagamentos.',en:'Organize interactions between customers and providers, connecting offers, orders, conversations and payments.'},built:{pt:['Frontend em Next.js e backend em Go/Gin.','Fluxos de ofertas e pedidos, comunicação por WebSocket e integração de pagamentos.','Ferramentas administrativas e operação técnica do produto durante o projeto.'],en:['Next.js frontend and Go/Gin backend.','Offer and order flows, WebSocket communication and payment integration.','Administrative tools and technical operation of the product during the project.']},learn:{pt:'O projeto comercial foi encerrado. O trabalho técnico permanece como experiência em fluxos de marketplace e integrações.',en:'The commercial project was discontinued. The engineering work remains experience in marketplace flows and integrations.'}},
 {id:'kalevo',name:'Kalevo',image:'/media/kalevo.jpg',url:'https://kalevo.com.br',category:'archived',role:'partner',kind:{pt:'EVENTOS / ESTUDO TÉCNICO',en:'EVENTS / ENGINEERING STUDY'},status:{pt:'Encerrado · antes Bregashow',en:'Archived · formerly Bregashow'},description:{pt:'Plataforma de eventos e ingressos, com painel de gestão, controle de acesso e recursos de streaming.',en:'An events and ticketing platform, with a management dashboard, access control and streaming features.'},stack:['Next.js','TypeScript','Supabase','PostgreSQL','Mux'],challenge:{pt:'Concentrar a publicação de eventos, venda de ingressos e operação de acesso em fluxos conectados.',en:'Bring event publication, ticket sales and entry operations together in connected workflows.'},built:{pt:['Experiência web em Next.js/TypeScript para eventos e gestão.','Integração com Supabase/PostgreSQL e recursos de streaming com Mux.','Fluxos de ingressos e validação de acesso por QR code.'],en:['Next.js/TypeScript web experience for events and management.','Supabase/PostgreSQL integration and streaming features with Mux.','Ticket workflows and QR-code entry validation.']},learn:{pt:'O produto foi encerrado. A experiência reúne frontend, dados, integrações e regras de operação de eventos.',en:'The product was discontinued. The experience combines frontend, data, integrations and event-operation rules.'}}
];
const architecture:Record<string,{pt:string,en:string}>={
zapyflow:{pt:'A interface organiza leads, conversas e fluxos visuais. A API em Fastify conecta essa operação à persistência com Prisma e à WhatsApp Cloud API. O fluxo de atendimento reúne automação, consulta à base de conhecimento e intervenção de um operador; integração externa e estado da conversa precisam ser considerados juntos.',en:'The interface organizes leads, conversations and visual workflows. A Fastify API connects these operations to Prisma persistence and the WhatsApp Cloud API. Support workflows combine automation, knowledge-base access and operator intervention; external integration and conversation state must be considered together.'},
vettano:{pt:'Autenticação, lobby, partidas e recursos sociais são organizados em serviços Go. PostgreSQL, Redis e NATS compõem a base de dados, estado e comunicação entre serviços. O reboot altera o cliente e a experiência visual: a versão anterior era web/React, e o cliente Godot/C# ainda está em desenvolvimento.',en:'Authentication, lobbies, matches and social features are organized in Go services. PostgreSQL, Redis and NATS support data, state and inter-service communication. The reboot changes the client and visual experience: the previous version was web/React, and the Godot/C# client is still under development.'},
infinity:{pt:'A experiência conecta compradores e prestadores por meio de ofertas e pedidos. O frontend Next.js conversa com a API Go/Gin; PostgreSQL mantém os dados e WebSocket atende à comunicação em tempo real. Pagamentos e mudanças no estado do pedido fazem parte do mesmo fluxo operacional. As capturas registram a interface construída, sem representar atividade comercial atual.',en:'The experience connects buyers and providers through offers and orders. The Next.js frontend talks to a Go/Gin API; PostgreSQL stores data and WebSocket supports real-time communication. Payments and order-state changes are part of the same operational workflow. The captures document the built interface, without implying current commercial activity.'},
kalevo:{pt:'A experiência pública de eventos se conecta a fluxos de ingressos e gestão. A aplicação Next.js/TypeScript usa Supabase/PostgreSQL, recursos de streaming com Mux e validação de acesso por QR code. O domínio público preserva uma versão do projeto; sua existência não representa continuidade comercial do empreendimento.',en:'The public event experience connects to ticketing and management workflows. The Next.js/TypeScript application uses Supabase/PostgreSQL, Mux streaming features and QR-code entry validation. The public domain preserves a version of the project; its availability does not imply continued commercial operations.'}
};
export default function Portfolio({locale}:{locale:Locale}) {
 const t=text[locale], [filter,setFilter]=useState('all'),[copied,setCopied]=useState(false),[copyFailed,setCopyFailed]=useState(false);
 const art=useRef<HTMLDivElement>(null);
 useEffect(()=>{document.documentElement.lang=locale==='pt'?'pt-BR':'en';const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:0.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));return ()=>observer.disconnect()},[locale,filter]);
 async function copyEmail(){try{await navigator.clipboard.writeText('nerilogic@gmail.com');setCopied(true);setCopyFailed(false)}catch{setCopyFailed(true)}}
 function moveArt(e:React.PointerEvent<HTMLElement>){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();art.current?.style.setProperty('--rx',`${((e.clientX-r.left)/r.width-.5)*9}deg`);art.current?.style.setProperty('--ry',`${((e.clientY-r.top)/r.height-.5)*-7}deg`)}
 return <>
 <a className="skip-link" href="#main">{t.skip}</a>
 <header className="site-header"><Link className="brand" href={`/${locale}`} aria-label="Daniel Neri"><span className="monogram">DN</span><span>Daniel Neri</span></Link><nav aria-label={locale==='pt'?'Navegação principal':'Main navigation'}>{t.nav.map((n,i)=><a key={n} href={`#${['projetos','sobre','contato'][i]}`}>{n}</a>)}</nav><div className="languages" aria-label="Language"><Link href="/pt" lang="pt-BR" aria-current={locale==='pt'?'page':undefined}>PT</Link><span>/</span><Link href="/en" lang="en" aria-current={locale==='en'?'page':undefined}>EN</Link></div></header>
 <main id="main">
 <section className="hero" onPointerMove={moveArt} onPointerLeave={()=>{art.current?.style.setProperty('--rx','0deg');art.current?.style.setProperty('--ry','0deg')}}>
 <div className="hero-copy"><p className="availability"><span/>{t.available}</p><h1>{t.hero}<br/><em>{t.heroEnd}</em></h1><p className="hero-sub">{t.sub}</p><p className="hero-intro">{t.intro}</p><div className="actions"><a className="button primary" href="#projetos">{t.explore}<span>↗</span></a><a className="button outline" href={`/resume/daniel-neri-${locale}.pdf`} target="_blank" rel="noopener noreferrer">{t.resume}<span>↓</span></a></div></div>
 <div className="hero-art" ref={art} aria-hidden="true"><Image src="/media/ilustracao-transparente.webp" alt="" priority sizes="(max-width: 650px) 120vw, 68vw" width="1536" height="1024"/><HeroSculpture/><span className="art-caption">DESIGN × ENGINEERING</span></div>
 <div className="hero-bottom"><span>BELÉM, BRASIL / REMOTE</span><span>REACT · TYPESCRIPT · GO</span><a href="#projetos" aria-label={t.explore}>↓</a></div></section>
 <section id="projetos" className="work section-pad"><div className="section-heading reveal"><p className="eyebrow">{t.selected}</p><div className="heading-row"><h2>{t.workTitle}<br/><em>{t.workEnd}</em></h2><p>{t.workIntro}</p></div></div>
 <div className="filter-bar" aria-label={locale==='pt'?'Filtrar projetos':'Filter projects'}>{['all','active','archived'].map((f,i)=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{t.filters[i]}<span>{[4,2,2][i].toString().padStart(2,'0')}</span></button>)}</div>
 <div className="project-list">{projects.filter(p=>filter==='all'||filter===p.category).map((p,i)=><article key={p.id} className={`project reveal ${p.category==='archived'?'archived':''}`}>
 <div className="project-media">{'image' in p&&p.image?<figure><Image src={p.image} alt={p.id==='vettano'?t.previous:p.id==='infinity'?(locale==='pt'?'Captura publicada no LinkedIn · projeto encerrado':'Capture published on LinkedIn · archived project'):t.capture} width="1440" height="900" sizes="(max-width: 650px) 88vw, 45vw"/><figcaption>{p.id==='vettano'?t.previous:p.id==='infinity'?(locale==='pt'?'Captura publicada no LinkedIn · projeto encerrado':'Capture published on LinkedIn · archived project'):t.capture}</figcaption></figure>:<div className={`archive-art ${p.id}`} aria-hidden="true"><span className="archive-symbol">{p.id==='infinity'?'∞':'k.'}</span><span>{p.name}</span><small>{t.archived}</small></div>}</div>
 <div className="project-copy"><div className="project-kicker"><span>{p.kind[locale]}</span><span>0{i+1}</span></div><p className="project-status"><span className={p.category==='active'?'status-dot':''}/>{p.status[locale]}</p><h3>{p.name}</h3><p className="role">{p.role==='founder'?t.founder:t.partner}</p><p className="description">{p.description[locale]}</p><ul className="tags" aria-label="Stack">{p.stack.map(s=><li key={s}>{s}</li>)}</ul>

 {'url' in p&&p.url&&<a className="text-link" href={p.url} target="_blank" rel="noopener noreferrer">{t.visit} ↗</a>}</div> <details className="project-study"><summary><span>{t.case}</span><span className="plus">+</span></summary><div className="case-body"><div className="case-section"><h4>{t.scope}</h4><p>{t.scopeText}</p></div><div className="case-section"><h4>{t.challenge}</h4><p>{p.challenge[locale]}</p></div><div className="case-section"><h4>{t.built}</h4><ul>{p.built[locale].map(b=><li key={b}>{b}</li>)}</ul></div><div className="case-section"><h4>{t.learn}</h4><p>{p.learn[locale]}</p></div><div className="case-section case-architecture"><h4>{locale==='pt'?'Arquitetura e fluxo':'Architecture and flow'}</h4><p>{architecture[p.id][locale]}</p></div>{p.id==='vettano'&&<div className="case-gallery">{['vettano-round','vettano-dev'].map((name,j)=><figure key={name}><a href={`/media/${name}.webp`} target="_blank" rel="noopener noreferrer"><Image src={`/media/${name}.webp`} width={2048} height={1152} sizes="(max-width:650px) 88vw, 35vw" alt={locale==='pt'?(j===0?'Vettano: resultado de uma rodada no redesign atual':'Vettano: simulação de desenvolvimento com desenho e jogadores'):(j===0?'Vettano: round result in the current redesign':'Vettano: development simulation with drawing and players')}/></a><figcaption>{locale==='pt'?(j===0?'Interface atual · resultado da rodada':'Simulação de desenvolvimento · interface atual'):(j===0?'Current interface · round result':'Development simulation · current interface')}</figcaption></figure>)}</div>}{p.id==='infinity'&&<div className="case-gallery">{['infinity-order','infinity-offer'].map((name,j)=><figure key={name}><a href={`/media/${name}.jpg`} target="_blank" rel="noopener noreferrer"><Image src={`/media/${name}.jpg`} width={480} height={254} sizes="(max-width:650px) 88vw, 35vw" alt={locale==='pt'?(j===0?'Configuração de pedido do Infinity Boost':'Detalhe de oferta do Infinity Boost'):(j===0?'Infinity Boost order configuration':'Infinity Boost offer detail')}/></a><figcaption>{locale==='pt'?'Captura do produto publicada no LinkedIn':'Product capture published on LinkedIn'}</figcaption></figure>)}</div>}</div></details></article>)}</div></section>
 <section id="sobre" className="about section-pad"><div className="about-grid"><div className="about-photo reveal"><Image src="/media/portrait.webp" alt={t.portrait} width="1254" height="1254" sizes="(max-width: 650px) 280px, 360px"/><div className="photo-label"><span>Daniel Neri</span><span>FULL STACK DEVELOPER</span></div></div><div className="about-copy reveal"><p className="eyebrow">{t.aboutLabel}</p><h2>{t.aboutTitle}<br/><em>{t.aboutEnd}</em></h2><p>{t.aboutText}</p><p>{t.aboutText2}</p><dl className="facts">{[[t.degree,t.degreeSub],[t.english,t.englishSub],[t.location,t.locationSub]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></div></div>
 <div className="toolbox reveal"><p className="eyebrow">{t.toolbox}</p><div>{['React / Next.js','TypeScript','Go','Godot / C#','PostgreSQL','Redis / NATS','Docker / Linux','APIs / WebSocket'].map(s=><span key={s}>{s}</span>)}</div></div></section>
 <section id="contato" className="contact section-pad"><div className="contact-main reveal"><p className="eyebrow">{t.contactLabel}</p><h2>{t.contactTitle}<br/><em>{t.contactEnd}</em></h2><p>{t.contactText}</p><a className="contact-email" href="mailto:nerilogic@gmail.com">nerilogic@gmail.com<span>↗</span></a><div className="contact-links"><button onClick={copyEmail}>{copied?t.copied:copyFailed?t.copyError:t.copy} <span aria-hidden="true">{copied?'✓':'⧉'}</span></button><a href="https://www.linkedin.com/in/daniel-neri-51a7b12b3/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/c7bc" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href={`/resume/daniel-neri-${locale}.pdf`} target="_blank" rel="noopener noreferrer">{t.docs} ↓</a></div><span className="sr-only" role="status">{copied?t.copied:copyFailed?t.copyError:''}</span></div><span className="contact-mark" aria-hidden="true">DN</span></section>
 </main><footer className="footer"><p>© {new Date().getFullYear()} · {t.footer}</p><a href="#main">{t.back} ↑</a><span>PT / EN</span></footer>
 </>;
}
